USE AI_Medical_Diagnosis;
GO
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D01', N'Prof. Eranga Wijewickrama', N'Consultant Nephrologist', N'Chronic Kidney Disease', N'Colombo');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D02', N'Prof. Rezvi Sheriff', N'Consultant Nephrologist', N'Chronic Kidney Disease', N'Colombo');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D03', N'Dr. Chula Herath', N'Consultant Nephrologist', N'Chronic Kidney Disease', N'Colombo');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D04', N'Dr. Anura Hewageegana', N'Consultant Nephrologist', N'Chronic Kidney Disease', N'Colombo');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D05', N'Dr. Mathu Selvarajah', N'Consultant Nephrologist', N'Chronic Kidney Disease', N'Colombo');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D06', N'Dr. Rajeewa Dassanayake', N'Consultant Nephrologist', N'Chronic Kidney Disease', N'Kandy');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D07', N'Dr. E.H.C. Keerthi Bandara', N'Consultant Nephrologist', N'Chronic Kidney Disease', N'Kandy');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D08', N'Dr. R. Nishantha Nanayakkara', N'Consultant Nephrologist', N'Chronic Kidney Disease', N'Kandy');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D09', N'Dr. A.W.M. Wazil', N'Consultant Nephrologist', N'Chronic Kidney Disease', N'Kandy');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D10', N'Dr. Harshani D. Perera', N'Consultant Nephrologist', N'Chronic Kidney Disease', N'Colombo');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D11', N'Dr. Uditha Dassanayake', N'Gastroenterologist & Hepatologist', N'Liver Disease', N'Colombo / Ragama');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D12', N'Prof. Madunil Niriella', N'Gastroenterologist & Hepatologist', N'Liver Disease', N'Ragama');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D13', N'Dr. Chathura Lakmal Piyarathna', N'Gastroenterologist & Hepatologist', N'Liver Disease', N'Kandy');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D14', N'Dr. Hasitha Wijewantha', N'Gastroenterologist & Hepatologist', N'Liver Disease', N'Kandy');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D15', N'Dr. N.P. Dinamithra', N'Gastroenterologist & Hepatologist', N'Liver Disease', N'Kandy');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D16', N'Dr. Udaya Kalubowila', N'Gastroenterologist & Hepatologist', N'Liver Disease', N'Kandy');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D17', N'Dr. W.G. Eranda Luxman', N'Gastroenterologist & Hepatologist', N'Liver Disease', N'Negombo');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D18', N'Dr. Hiruni Jayasena', N'Gastroenterologist & Hepatologist', N'Liver Disease', N'Colombo');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D19', N'Dr. Tilan Aponso', N'Gastroenterologist & Hepatologist', N'Liver Disease', N'Colombo');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D20', N'Dr. Karthiha Balendran', N'Gastroenterologist & Hepatologist', N'Liver Disease', N'Jaffna');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D21', N'Dr. Ajith Kularathne', N'Consultant Cardiologist', N'Heart Disease', N'Kandy');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D22', N'Dr. Anidu Pathirana', N'Consultant Cardiologist', N'Heart Disease', N'Colombo');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D23', N'Dr. Gamini Galappaththy', N'Consultant Cardiologist', N'Heart Disease', N'Colombo');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D24', N'Dr. Bhathiya Ranasinghe', N'Consultant Cardiologist', N'Heart Disease', N'Colombo');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D25', N'Dr. Jagath Herath', N'Consultant Cardiologist', N'Heart Disease', N'Colombo');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D26', N'Dr. Ruwan Munasinghe', N'Consultant Cardiologist', N'Heart Disease', N'Colombo');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D27', N'Dr. S. Narenthiren', N'Consultant Cardiologist', N'Heart Disease', N'Colombo');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D28', N'Dr. Namal Wijesinghe', N'Consultant Cardiologist', N'Heart Disease', N'Colombo');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D29', N'Dr. Rohini Tennakoon', N'Consultant Cardiologist', N'Heart Disease', N'Kandy');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D30', N'Dr. K. Suntharesan', N'Consultant Cardiologist', N'Heart Disease', N'Kandy');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D31', N'Dr. Prasad Katulanda', N'Consultant Endocrinologist', N'Diabetes', N'Colombo');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D32', N'Dr. Uditha Bulugahapitiya', N'Consultant Endocrinologist', N'Diabetes', N'Colombo');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D33', N'Dr. Manilka Sumanatilleke', N'Consultant Endocrinologist', N'Diabetes', N'Colombo');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D34', N'Dr. Sajith Siyambalapitiya', N'Consultant Endocrinologist', N'Diabetes', N'Colombo');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D35', N'Dr. Chaminda Garusinghe', N'Consultant Endocrinologist', N'Diabetes', N'Colombo');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D36', N'Dr. Noel Somasundaram', N'Consultant Endocrinologist', N'Diabetes', N'Colombo');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D37', N'Dr. Sivatharshya Pathmanathan', N'Consultant Endocrinologist', N'Diabetes', N'Colombo');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D38', N'Dr. Charles Antonypillai', N'Consultant Endocrinologist', N'Diabetes', N'Kandy');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D39', N'Dr. Sachith Abhayaratna', N'Consultant Endocrinologist', N'Diabetes', N'Colombo');
INSERT INTO dbo.Doctors ([DoctorId], [DoctorName], [Specializes], [Disease], [Location]) VALUES (N'D40', N'Dr. Samandhi Cooray', N'Consultant Endocrinologist', N'Diabetes', N'Colombo');
GO
