USE AI_Medical_Diagnosis;
GO
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Chronic Kidney Disease', N'Fatigue');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Chronic Kidney Disease', N'Swelling of feet and ankles');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Chronic Kidney Disease', N'Weakness');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Chronic Kidney Disease', N'Swelling around eyes');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Chronic Kidney Disease', N'Frequent urination');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Chronic Kidney Disease', N'Reduced urine output');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Chronic Kidney Disease', N'Foamy urine');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Chronic Kidney Disease', N'Blood in urine');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Chronic Kidney Disease', N'Dark or cloudy urine');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Chronic Kidney Disease', N'Difficulty sleeping');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Chronic Kidney Disease', N'Muscle cramps');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Chronic Kidney Disease', N'Muscle weakness');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Chronic Kidney Disease', N'Itchy skin');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Chronic Kidney Disease', N'Dry skin');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Chronic Kidney Disease', N'Nausea');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Chronic Kidney Disease', N'Vomiting');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Chronic Kidney Disease', N'Loss of appetite');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Chronic Kidney Disease', N'Weight loss');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Chronic Kidney Disease', N'Headache');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Chronic Kidney Disease', N'Difficulty concentrating');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Chronic Kidney Disease', N'Shortness of breath');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Chronic Kidney Disease', N'Chest discomfort');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Chronic Kidney Disease', N'High blood pressure');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Chronic Kidney Disease', N'Metallic taste in mouth');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Chronic Kidney Disease', N'Bad breath');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Heart Disease', N'Chest pain');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Heart Disease', N'Chest pressure');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Heart Disease', N'Chest tightness');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Heart Disease', N'Shortness of breath');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Heart Disease', N'Fatigue');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Heart Disease', N'Weakness');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Heart Disease', N'Dizziness');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Heart Disease', N'Fainting');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Heart Disease', N'Rapid heartbeat');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Heart Disease', N'Irregular heartbeat');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Heart Disease', N'Palpitations');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Heart Disease', N'Sweating');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Heart Disease', N'Nausea');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Heart Disease', N'Vomiting');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Heart Disease', N'Pain in left arm');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Heart Disease', N'Pain in both arms');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Heart Disease', N'Shoulder pain');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Heart Disease', N'Neck pain');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Heart Disease', N'Jaw pain');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Heart Disease', N'Back pain');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Heart Disease', N'Cold sweat');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Heart Disease', N'Swelling of legs');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Heart Disease', N'Reduced exercise tolerance');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Heart Disease', N'Difficulty breathing when lying down');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Heart Disease', N'Breathlessness during activity');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Diabetes', N'Frequent urination');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Diabetes', N'Excessive thirst');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Diabetes', N'Increased hunger');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Diabetes', N'Unexplained weight loss');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Diabetes', N'Fatigue');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Diabetes', N'Weakness');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Diabetes', N'Blurred vision');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Diabetes', N'Slow-healing wounds');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Diabetes', N'Frequent infections');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Diabetes', N'Recurrent urinary infections');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Diabetes', N'Itchy skin');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Diabetes', N'Dry skin');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Diabetes', N'Tingling in hands');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Diabetes', N'Tingling in feet');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Diabetes', N'Numbness in hands');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Diabetes', N'Numbness in feet');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Diabetes', N'Burning sensation in feet');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Diabetes', N'Increased sweating');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Diabetes', N'Headache');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Diabetes', N'Irritability');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Diabetes', N'Difficulty concentrating');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Diabetes', N'Nausea');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Diabetes', N'Dry mouth');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Diabetes', N'Fruity-smelling breath');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Diabetes', N'Reduced energy');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Liver Disease', N'Fatigue');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Liver Disease', N'Weakness');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Liver Disease', N'Loss of appetite');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Liver Disease', N'Nausea');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Liver Disease', N'Vomiting');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Liver Disease', N'Abdominal pain');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Liver Disease', N'Abdominal swelling');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Liver Disease', N'Swelling of legs');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Liver Disease', N'Jaundice');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Liver Disease', N'Dark urine');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Liver Disease', N'Pale or clay-colored stool');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Liver Disease', N'Itchy skin');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Liver Disease', N'Easy bruising');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Liver Disease', N'Easy bleeding');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Liver Disease', N'Weight loss');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Liver Disease', N'Weight gain due to fluid retention');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Liver Disease', N'Confusion');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Liver Disease', N'Difficulty concentrating');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Liver Disease', N'Sleep problems');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Liver Disease', N'Swelling around the abdomen');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Liver Disease', N'Spider-like blood vessels on skin');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Liver Disease', N'Red palms');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Liver Disease', N'Muscle loss');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Liver Disease', N'Bad breath');
INSERT INTO dbo.Symptoms ([Disease], [Symptom]) VALUES (N'Liver Disease', N'Fever');
GO
